### ISSUE TITLE
[Bug] computing thumbnails from lfw

### ISSUE THREAD

**Issue by JoelGardes** [Orange-OpenSource/documentare-simdoc#16]
Thumbnail 0.png not produced. Message : 

Exception in thread "main" com.orange.documentare.core.comp.nativeinterface.NativeException: Command line 'convert /home/jyig5563/lfw/lfw-deepfunneled/Aaron_Peirsol/._Aaron_Peirsol_0004.jpg[0] -thumbnail x300 -background white -alpha remove -polaroid -0 /home/jyig5563/lfw/thumbnails/0.png  > /home/jyig5563/lfw/thumbnails/0.png.log' returned error code 1
	at com.orange.documentare.core.comp.nativeinterface.NativeInterface.launchCmd(NativeInterface.java:59)
	at com.orange.documentare.core.comp.nativeinterface.NativeInterface.launch(NativeInterface.java:48), etc...

All other thumbnails OK, traces of NCD joined
[trace.txt](https://github.com/Orange-OpenSource/documentare-simdoc/files/654433/trace.txt)

**Comment by JoelGardes** [comment]
to be discussed before next sprint, normally corrected with symbolic links used as metadata

**Comment by JoelGardes** [comment]
OK with 1.30 version
